#! /bin/sh
# /etc/init.d/sendip

# The following part always gets executed.
echo "This part always gets executed"
python /home/yosuke/raspip/raspip.py

# The following part carries out specific functions depending on arguments.
case "$1" in
  start)
    echo "Starting raspip"
    echo "Sending email"
    ;;
  stop)
    echo "Stopping raspip"
    ;;
  *)
    echo "Usage: /etc/init.d/foobar {start|stop}"
    exit 1
    ;;
esac

exit 0
